"""add clicks_count and indexes to links

Revision ID: 71bf030717d4
Revises: 5ef384ccd9ab
Create Date: 2026-03-14 19:46:08.092038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bf030717d4'
down_revision: Union[str, Sequence[str], None] = '5ef384ccd9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('clicks_count', sa.Integer(), nullable=False))
    op.create_index('ix_links_deleted_at', 'links', ['deleted_at'], unique=False)
    op.create_index('ix_links_original', 'links', ['original'], unique=False)
    op.create_index('ix_links_short', 'links', ['short'], unique=False)
    op.create_unique_constraint(None, 'links', ['short'])
    op.create_unique_constraint(None, 'links', ['alias'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='unique')
    op.drop_constraint(None, 'links', type_='unique')
    op.drop_index('ix_links_short', table_name='links')
    op.drop_index('ix_links_original', table_name='links')
    op.drop_index('ix_links_deleted_at', table_name='links')
    op.drop_column('links', 'clicks_count')
    # ### end Alembic commands ###
